wandb:
    project_name: "10_2022_calibration_test"
    project_team: 'tail-upenn'
    online: True

project:
    device: 'gpu'
    num_workers: 12
    num_epochs: 200
    pin_memory: True
    load_model: False
    val_interval: 5
    time: 0
    epoch: 0 

hyperparameters:
    batch_size: 8
    weights: True
    
    optimizer_fn: adam
        
    adam_learning_rate: .0003

    sgd_learning_rate: .01
    sgd_momentum: 0.9
    sgd_weight_decay: .0001
    sgd_nesterov: True

    loss_fn: crossentropy   
    multiplier: [1,1,1,1]
            
    tversky_alpha: .5
    tversky_beta: .5

    focal_alpha: 1
    focal_gamma: 2
    
    scheduler_fn: warm
    scheduler_patience: 5
    
    earlystopping: True
    earlystop_patience: 10
    earlystop_wait: 10

model:
    max_layer_size: 1024
    min_layer_size: 64

calibration:
    custom: False

image:
    phantom_format: 'dcm'
    mask_format: 'png'
    image_height: 600
    image_width: 360
    image_channels: 1
    mask_channels: 1
    mask_labels: 4

    labels: 
        0: 'background' 
        1: 'low_risk'
        2: 'moderate_risk'
        3: 'high_risk'

load:
    path: None

paths:
    train_img_dir: "E:/yann_folder/sweep_2022/2022-05-data/train/phantom/"
    train_mask_dir: "E:/yann_folder/sweep_2022/2022-05-data/train/mask/"
    val_img_dir: "E:/yann_folder/sweep_2022/2022-05-data/val/phantom/"
    val_mask_dir: "E:/yann_folder/sweep_2022/2022-05-data/val/mask/"
    test_img_dir: "E:/yann_folder/sweep_2022/2022-05-data/test/phantom/"
    test_mask_dir: "E:/yann_folder/sweep_2022/2022-05-data/test/mask/"
    predictions_dir: "data/predictions/"
    submissions_dir: "data/submissions/"
    calibrations_dir: "data/calibrations/"
    confidences_dir: "data/confidences/"