PROJECT:
  NUM_WORKERS: 12
  PROJECT_NAME: "2022_old"
  PROJECT_TEAM: 'tail-upenn'
  SCHEDULER: True
  EARLYSTOP: True
  PIN_MEMORY: True
  LOAD_MODEL: False
  VALIDATION_INTERVAL: 20

HYPERPARAMETERS:
  LEARNING_RATE: .0001
  BATCH_SIZE: 14
  MAX_NUM_EPOCHS: 250
  OPTIMIZER: 'adam'
  LOSS_FUNCTION: 'crossentropy'
  MAX_LAYER_SIZE: 1024
  MIN_LAYER_SIZE: 64
  WEIGHTS: True
  MULTIPLIER: [1,1,1,1]

IMAGE:
  IMAGE_HEIGHT: 512
  IMAGE_WIDTH: 301
  IMAGE_CHANNELS: 1
  MASK_CHANNELS: 1
  MASK_LABELS: 4
  PHANTOM_FORMAT: 'tiff'
  MASK_FORMAT: 'png'

PATHS:
  TRAIN_IMG_DIR: "data/train/phantom/"
  TRAIN_MASK_DIR: "data/train/mask/"
  VAL_IMG_DIR: "data/val/phantom/"
  VAL_MASK_DIR: "data/val/mask/"
  TEST_IMG_DIR: "data/test/phantom/"
  TEST_MASK_DIR: "data/test/mask/"
  PREDICTIONS_DIR: "data/predictions/"
  SUBMISSIONS_DIR: "data/submissions/"