wandb:
    project_name: "10_2022_calibration_test"
    project_team: 'tail-upenn'
    online: True

project:
    device: 'gpu'
    num_workers: 12
    num_epochs: 3
    pin_memory: True
    load_model: False
    val_interval: 2
    time: 0
    epoch: 0 

hyperparameters:
    batch_size: 8
    weights: True
    
    optimizer: 
        name: adam
        
        adam:
            learning_rate: .0003

        sgd:
            learning_rate: .01
            momentum: 0.9
            weight_decay: .0001
            nesterov: True

    loss: 
        name: crossentropy

        crossentropy:
            multiplier: [1,1,1,1]
            
        tversky:
            alpha: .5
            beta: .5

        focal:
            alpha: 1
            gamma: 2
    
    scheduler: 
        name: warm
        patience: 5
    
    earlystop:
        earlystopping: True
        patience: 10

model:
    max_layer_size: 1024
    min_layer_size: 64

calibration:
    custom: False

image:
    phantom_format: 'dcm'
    mask_format: 'png'
    image_height: 600
    image_width: 360
    image_channels: 1
    mask_channels: 1
    mask_labels: 4

    labels: 
        0: 'background' 
        1: 'low_risk'
        2: 'moderate_risk'
        3: 'high_risk'

load:
    path: None

paths:
    train_img_dir: "D:/MamAria/data/train/phantom/"
    train_mask_dir: "D:/MamAria/data/train/mask/"
    val_img_dir: "D:/MamAria/data/val/phantom/"
    val_mask_dir: "D:/MamAria/data/val/mask/"
    test_img_dir: "D:/MamAria/data/test/phantom/"
    test_mask_dir: "D:/MamAria/data/test/mask/"
    predictions_dir: "data/predictions/"
    submissions_dir: "data/submissions/"
    calibrations_dir: "data/calibrations/"
    confidences_dir: "data/confidences/"