wandb:
    project_name: "6_2022_sweep"
    project_team: 'tail-upenn'
    online: False

time: 0
epoch: 0 

project:
    device: 'gpu'
    num_workers: 12
    max_num_epochs: 250

    scheduler: True
    earlystop: True
    pin_memory: True
    load_model: False
    validation_interval: 20


hyperparameters:
    optimizer: 'adam'
    loss_function: 'crossentropy'
    weights: True
    
    batch_size: 16
    multiplier: [1,1,1,1]
    
    adam_learning_rate: .0003
    
    sgd_learning_rate: .01
    sgd_momentum: 0.9
    sgd_weight_decay: .0001
    sgd_nesterov: True
    
    tversky_alpha: .5
    tversky_beta: .5

    focal_alpha: 1
    focal_gamma: 2

    earlystopping_wait: 10
    earlystopping_patience: 10

model:
    max_layer_size: 1024
    min_layer_size: 64

image:
    image_height: 600 #512
    image_width: 360 #301
    image_channels: 1
    mask_channels: 1
    mask_labels: 4
    phantom_format: 'tiff'
    mask_format: 'png'
    labels: 
        0: 'background' 
        1: 'low_risk'
        2: 'moderate_risk'
        3: 'high_risk'

paths:
    train_img_dir: "C:/Users/yannn/Documents/GitHub/MamAria/2022-05/data/train/phantom/"
    train_mask_dir: "C:/Users/yannn/Documents/GitHub/MamAria/2022-05/data/train/mask/"
    val_img_dir: "C:/Users/yannn/Documents/GitHub/MamAria/2022-05/data/val/phantom/"
    val_mask_dir: "C:/Users/yannn/Documents/GitHub/MamAria/2022-05/data/val/mask/"
    test_img_dir: "C:/Users/yannn/Documents/GitHub/MamAria/2022-05/data/test/phantom/"
    test_mask_dir: "C:/Users/yannn/Documents/GitHub/MamAria/2022-05/data/test/mask/"
    predictions_dir: "C:/Users/yannn/Documents/GitHub/MamAria/2022-05/data/predictions/"
    submissions_dir: "C:/Users/yannn/Documents/GitHub/MamAria/2022-05/data/submissions/"