sweep_config = {
    'method' 'grid', # grid, random
    'metric' {
      'name' 'loss',
      'goal' 'minimize'   
    },
    'parameters' {
        'MULTIPLIER'{
            'values'[[1,1,1,1], [1,1,1,2], [1,1,2,2], [1,1,2,1], [1,2,2,1], [1,2,1,2]]
        },
        # 'optimizer' {
        #     'values' ['adam', 'sgd']
        # },
    }
}