defaults:
  - _self_

_target_: src.datamodule.phantom.PhantomData
dataset:
  _target_: src.dataset.phantom.PhantomDCMDataset
  _partial_: true
  image_size: [2816, 3584]

data_dir: ${paths.data_dir}

val_size: 0.3

num_classes: ${num_classes}
num_workers: ${num_workers}
batch_size: ${batch_size}
transforms: ${transforms}
