defaults:
  - _self_

_target_: src.datamodule.phantom.PhantomData
dataset:
  _partial_: true
  _target_: src.dataset.phantom.PhantomTiffDataset

data_dir: ${paths.data_dir}

val_size: 0.3

num_classes: ${num_classes}
num_workers: ${num_workers}
batch_size: ${batch_size}
transforms: ${transforms}
