defaults:
  - _self_
  - paths: default
  - trainer: default
  - datamodule: dicom
  - module: unet
  - loggers: default
  - callbacks: default
  - transforms: default
  - lr_scheduler: plateau
  - loss_fn: focal_tversky
  - optimizer: adamw
  - metrics: default

# general

precision: medium
num_classes: 4
image_size: [360, 600]
task: testing
seed: null
model_name: unet
label_map:
  0: background
  1: low_risk
  2: moderate_risk
  3: high_risk

multiplier: [1, 1, 1, 1]

# system

accelerator: gpu
num_workers: 12
batch_size: 4
profiler:
  null
  # _target_: lightning.pytorch.profilers.SimpleProfiler

# logging

mode: online
tags: null

# paths

root: /mnt/d/Github/MamAria/data

ckpt_path: null
